apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-frontend
  template:
    metadata:
      labels:
        app: my-frontend
    spec:
      containers:
        - name: web
          image: gcr.io/serovicloud2025/web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: STORAGE_SVC
              value: "storage"
          livenessProbe:
            httpGet:
              path: /phrase
              port: 8000
            periodSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: "web"
spec:
  selector:
    app: my-frontend 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer